# Generated by Django 4.2.11 on 2024-05-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
